---
title: "tripInformation"
author: "Chris Tufts"
date: "February 19, 2015"
output: html_document
---

The plot above displays the x and y coordinates for driver #2.  All of driver #2's trips are available for viewing. 
Below is the description of trip data from <http://www.kaggle.com/c/axa-driver-telematics-analysis/data>:

In order to protect the privacy of the drivers' location, the trips were centered to start at the origin (0,0), randomly rotated, and short lengths of trip data were removed from the start/end of the trip.

A small and random number of false trips (trips that were not driven by the driver of interest) are planted in each driver's folder. These false trips are sourced from drivers not included in the competition data, in order to prevent similarity analysis between the included drivers. You are not given the number of false trips (it varies), nor a labeled training set of true positive trips. You can safely make the assumption that the majority of the trips in each folder do belong to the same driver.